### ISSUE TITLE
[Meta] CoreLib implementation

### ISSUE THREAD

**Issue by asadali214** [apimatic/core-lib-php#1]
Implement the Core library for php using the [RFC](https://docs.google.com/document/d/1pFQAcvpzIF29yUHirMK7vu1j2II56oP1a7ly4FYJ8Jg/edit#)

Following are the identified tasks:
- [x] Create a basic structure for a PHP Library using test driven approach
- [x] Add CI/CD
- [x] Addition of Auth and CoreAuth classes with unit tests
- [x] Separate packages for types of Request and Response with Unit tests
- [x] Add all configuration setters required by PHP SDK in CoreConfig with Unit tests
- [x] Move all the utilities that are used by PHP SDKs with Unit tests
- [x] Creation of ApiCallBuilder with Unit tests in Core Package
- [x] Introduction of compatibilityFactory in Core Package with Unit tests
- [x] Creation of RequestBuilder and ResponseHandler with Unit tests in Core Package
- [x] Creation of all Parameter types with Unit tests in Core Package
- [x] Creation of CoreTestCase with Unit tests in Core Package
- [x] Creation of TestParam with Unit tests in Core Package
- [x] Wrapping of JsonMapper with Unit tests
- [x] Wrapping of UnirestPHP with Unit tests
- [x] Separation of Square's ApiResponse and normal ApiResponse
- [x] #3
## CoreLib Class Diagram:
![image](https://user-images.githubusercontent.com/26116671/179161230-3fec745f-e4ef-4628-a6d8-1b6e69acf403.png)

## CorePackage Class Diagram:
![image](https://user-images.githubusercontent.com/26116671/179159933-7bb7af63-c51c-4a6a-9219-02fe3b533829.png)
